name: zotit
description: Zot It Anywhere.
publish_to: 'none'
version: 1.5.1+33
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_expandable_fab: ^2.0.0
  flutter_linkify: ^6.0.0
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  gap: ^3.0.0
  google_fonts: ^6.0.0
  http: ^1.0.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1
  share_plus: 7.0.2
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.11
dev_dependencies:
  build_runner: ^2.4.4
  custom_lint: ^0.6.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  json_serializable: ^6.6.2
  riverpod_generator: ^2.2.3
  riverpod_lint: ^2.3.7
flutter:
  uses-material-design: true
  fonts:
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf
          style: italic
